apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models
  labels:
    app: ollama
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ollama
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ollama
    spec:
      containers:
      - image: ollama/ollama
        name: ollama
        ports:
          - containerPort: 11434
            name: llamaport
            protocol: TCP
        resources:
          requests:
            cpu: 1
            memory: 512M
          limits:
            cpu: 1
            memory: 2048M
        volumeMounts:
          - name: ollama-models
            mountPath: /root/.ollama
      volumes:
        - name: ollama-models
          persistentVolumeClaim:
            claimName: ollama-models
status: {}
