apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ollama
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ollama
    spec:
      containers:
      - image: ollama/ollama
        name: ollama
        ports:
          - containerPort: 11434
            name: llamaport
            protocol: TCP
        resources:
          requests:
            nvidia.com/gpu: 1
            memory: 4096M
          limits:
            nvidia.com/gpu: 1
            memory: 4096M

