apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ollama
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ollama
    spec:
      containers:
      - env:
        - name: OLLAMA_MODELS
          value: /data/models/ollama
        image: ollama/ollama
        name: ollama
        ports:
          - containerPort: 11434
            name: llamaport
            protocol: TCP
        resources:
          requests:
            nvidia.com/gpu: 1
            memory: 4096M
          limits:
            nvidia.com/gpu: 1
            memory: 4096M
        volumeMounts:
          - name: models-ro
            mountPath: /data/models
            readOnly: false
      volumes:
        - name: models-ro
          persistentVolumeClaim:
            claimName: models-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ollama
  name: ollama
spec:
  ports:
  - port: 11434
    protocol: TCP
    targetPort: 11434
  selector:
    app: ollama
---

