apiVersion: v1
kind: Service
metadata:
  labels:
    app: ollama-qwen3-ro
  name: ollama-qwen3-ro
spec:
  ports:
  - port: 11434
    protocol: TCP
    targetPort: 11434
  selector:
    app: ollama-qwen3-ro
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ollama-qwen-coder
  name: ollama-qwen-coder
spec:
  ports:
  - port: 11434
    protocol: TCP
    targetPort: 11434
  selector:
    app: ollama-qwen-coder
status:
  loadBalancer: {}
