#apiVersion: v1
#kind: Pod
#metadata:
#  name: gpu-test-volume
#spec:
#  restartPolicy: OnFailure
#  containers:
#  - name: ctr
#    image: ubuntu:22.04
#    command: ["sleep", "3600"]
#    resources:
#      limits:
#        nvidia.com/gpu: 1
#    volumeMounts:
#      - name: models-ro
#        mountPath: /data/models
#        readOnly: true
#  volumes:
#    - name: models-ro
#      persistentVolumeClaim:
#        claimName: models-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-volume-rw
spec:
  restartPolicy: OnFailure
  containers:
  - name: ctr
    image: ubuntu:22.04
    command: ["sleep", "3600"]
    resources:
      limits:
        nvidia.com/gpu: 1
    volumeMounts:
      - name: models-ro
        mountPath: /data/models
        readOnly: false
  volumes:
    - name: models-ro
      persistentVolumeClaim:
        claimName: models-pvc
---

